title: Raku Ramblings
description: Notes on Raku, Linux, PDF, and whatever else seems interesting.
url: "https://raku-ramblings.blog"

markdown: kramdown

theme: minima

permalink: /:title/

header_pages:
  - raku.md
  - about.md
